//
//  UITextField+TextColor.m
//  UITextField+TextColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UITextField+TextColor.h"
#import "DKNightVersionManager.h"
#import "objc/runtime.h"

@interface UITextField ()

@end

@implementation UITextField (TextColor)

- (DKColorPicker)textColorPicker {
    return objc_getAssociatedObject(self, @selector(textColorPicker));
}

- (void)setTextColorPicker:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(textColorPicker), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.textColor = picker();
    [self.pickers setValue:picker forKey:@"setTextColor:"];
}


@end
