//
//  UIButton+BackgroundColor.m
//  UIButton+BackgroundColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import "UIButton+backgroundColor.h"

#import "UIView+backgroundColor.h"

#import "DKNightVersionManager.h"

@implementation UIButton (BackgroundColor)

- (UIColor *)defaultNightBackgroundColor {
    return self.normalBackgroundColor;
}

@end
