//
//  UIButton+TintColor.m
//  UIButton+TintColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import "UIButton+tintColor.h"

#import "UIView+tintColor.h"

#import "DKNightVersionManager.h"

@implementation UIButton (TintColor)

- (UIColor *)defaultNightTintColor {
    return self.normalTintColor;
}

@end
