//
//  UIView+BackgroundColor.m
//  UIView+BackgroundColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIView+BackgroundColor.h"
#import "DKNightVersionManager.h"
#import "objc/runtime.h"

@interface UIView ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;

@end

@implementation UIView (BackgroundColor)

- (DKColorPicker)backgroundColorPicker {
    return objc_getAssociatedObject(self, @selector(backgroundColorPicker));
}

- (void)setBackgroundColorPicker:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(backgroundColorPicker), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.backgroundColor = picker();
    [self.pickers setValue:[picker copy] forKey:@"setBackgroundColor:"];
}


@end
