//
//  UIButton+TitleColor.m
//  UIButton+TitleColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIButton+TitleColor.h"
#import "DKNightVersionManager.h"
#import "objc/runtime.h"

@interface UIButton ()

@end

@implementation UIButton (TitleColor)

- (UIColor *)nightTitleColor {
    UIColor *nightColor = objc_getAssociatedObject(self, @selector(nightTitleColor));
    if (nightColor) {
        return nightColor;
    } else if (self.normalTitleColor) {
        return self.normalTitleColor;
    } else {
        return self.currentTitleColor;
    }
}

- (void)setNightTitleColor:(UIColor *)nightTitleColor {
    if ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNight) {
        if (!self.normalTitleColor) {
            self.normalTitleColor = self.currentTitleColor;
        }
        [self setTitleColor:nightTitleColor forState:UIControlStateNormal];
    } else {
        [self setTitleColor:self.normalTitleColor forState:UIControlStateNormal];
    }
    objc_setAssociatedObject(self, @selector(nightTitleColor), nightTitleColor, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

- (UIColor *)normalTitleColor {
    return objc_getAssociatedObject(self, @selector(normalTitleColor));
}

- (void)setNormalTitleColor:(UIColor *)normalTitleColor {
    if ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNormal) {
        [self setTitleColor:normalTitleColor forState:UIControlStateNormal];
    } else {
        [self setTitleColor:self.nightTitleColor forState:UIControlStateNormal];
    }
    objc_setAssociatedObject(self, @selector(normalTitleColor), normalTitleColor, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

@end
