//
//  UIBarButtonItem+TintColor.m
//  UIBarButtonItem+TintColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIBarButtonItem+TintColor.h"
#import "DKNightVersionManager.h"
#import "objc/runtime.h"

@interface UIBarButtonItem ()

@property (nonatomic, strong) NSMutableDictionary<NSString *, DKColorPicker> *pickers;

@end

@implementation UIBarButtonItem (TintColor)

- (DKColorPicker)tintColorPicker {
    return objc_getAssociatedObject(self, @selector(tintColorPicker));
}

- (void)setTintColorPicker:(DKColorPicker)picker {
    objc_setAssociatedObject(self, @selector(tintColorPicker), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.tintColor = picker();
    [self.pickers setValue:[picker copy] forKey:@"setTintColor:"];
}


@end
