//
//  UIBarButtonItem+TintColor.m
//  UIBarButtonItem+TintColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UIBarButtonItem+TintColor.h"
#import "DKNightVersionManager.h"
#import "objc/runtime.h"

@interface UIBarButtonItem ()

@end

@implementation UIBarButtonItem (TintColor)

- (UIColor *)nightTintColor {
    UIColor *nightColor = objc_getAssociatedObject(self, @selector(nightTintColor));
    if (nightColor) {
        return nightColor;
    } else if (self.normalTintColor) {
        return self.normalTintColor;
    } else {
        return self.tintColor;
    }
}

- (void)setNightTintColor:(UIColor *)nightTintColor {
    if ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNight) {
        if (!self.normalTintColor) {
            self.normalTintColor = self.tintColor;
        }
        [self setTintColor:nightTintColor];
    } else {
        [self setTintColor:self.normalTintColor];
    }
    objc_setAssociatedObject(self, @selector(nightTintColor), nightTintColor, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

- (UIColor *)normalTintColor {
    return objc_getAssociatedObject(self, @selector(normalTintColor))?: [UIColor blueColor];
}

- (void)setNormalTintColor:(UIColor *)normalTintColor {
    if ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNormal) {
        [self setTintColor:normalTintColor];
    } else {
        [self setTintColor:self.nightTintColor];
    }
    objc_setAssociatedObject(self, @selector(normalTintColor), normalTintColor, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

@end
