//
//  UILabel+TintColor.m
//  UILabel+TintColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import "UILabel+tintColor.h"
#import "DKNightVersionManager.h"
#import "UIView+tintColor.h"


@implementation UILabel (TintColor)

- (UIColor *)defaultNightTintColor {
    if ([self isMemberOfClass:[UILabel class]]) { 
        return UIColorFromRGB(0xffffff);
    } else {
        UIColor *resultColor = self.normalTintColor ?: [UIColor clearColor];
        return resultColor;
    }
}

@end
