//
//  UITableViewCell+BackgroundColor.m
//  UITableViewCell+BackgroundColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import "UITableViewCell+BackgroundColor.h"
#import "DKNightVersionManager.h"
#import "UIView+backgroundColor.h"


@implementation UITableViewCell (BackgroundColor)

- (UIColor *)defaultNightBackgroundColor {
    //BOOL notUIKitSubclass = [self isKindOfClass:[UITableViewCell class]] && ![NSStringFromClass(self.class) containsString:@"UI"];
    //if ([self isMemberOfClass:[UITableViewCell class]] || notUIKitSubclass) {
    if ([self isMemberOfClass:[UITableViewCell class]]) {
        return UIColorFromRGB(0x343434);
    } else {
        UIColor *resultColor = self.normalBackgroundColor ?: [UIColor clearColor];
        return resultColor;
    }
}

@end
