//
//  UITableViewCell+NightVersion.h
//  UITableViewCell+NightVersion
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "UITableViewCell+BackgroundColor.h"


@interface UITableViewCell (NightVersion)

- (void)changeColor;

- (void)changeColorWithDuration:(CGFloat)duration;

@end
