//
//  UINavigationBar+TintColor.m
//  UINavigationBar+TintColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import "UINavigationBar+TintColor.h"
#import "DKNightVersionManager.h"
#import "UIView+tintColor.h"


@implementation UINavigationBar (TintColor)

- (UIColor *)defaultNightTintColor {
    BOOL notUIKitSubclass = [self isKindOfClass:[UINavigationBar class]] && ![NSStringFromClass(self.class) containsString:@"UI"]; 
    if ([self isMemberOfClass:[UINavigationBar class]] || notUIKitSubclass)  { 
        return UIColorFromRGB(0xffffff);
    } else {
        UIColor *resultColor = self.normalTintColor ?: [UIColor clearColor];
        return resultColor;
    }
}

@end
