//
//  UINavigationBar+BarTintColor.h
//  UINavigationBar+BarTintColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>

@interface UINavigationBar (BarTintColor)

/**
 * Set this property when switch to night version uinavigationbar BarTintColor turns to this color.
 */
@property (nonatomic, strong) UIColor *nightBarTintColor;

/**
 *  UINavigationBar BarTintColor in normal version.
 */
@property (nonatomic, strong, readonly) UIColor *normalBarTintColor;

@end
