//
//  UINavigationBar+BarTintColor.m
//  UINavigationBar+BarTintColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UINavigationBar+BarTintColor.h"
#import "DKNightVersionManager.h"
#import "objc/runtime.h"

@interface UINavigationBar ()

@end

@implementation UINavigationBar (BarTintColor)

- (UIColor *)nightBarTintColor {
    UIColor *nightColor = objc_getAssociatedObject(self, @selector(nightBarTintColor));
    if (nightColor) {
        return nightColor;
    } else if (self.normalBarTintColor) {
        return self.normalBarTintColor;
    } else {
        return self.barTintColor;
    }
}

- (void)setNightBarTintColor:(UIColor *)nightBarTintColor {
    if ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNight) {
        if (!self.normalBarTintColor) {
            self.normalBarTintColor = self.barTintColor;
        }
        [self setBarTintColor:nightBarTintColor];
    } else {
        [self setBarTintColor:self.normalBarTintColor];
    }
    objc_setAssociatedObject(self, @selector(nightBarTintColor), nightBarTintColor, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

- (UIColor *)normalBarTintColor {
    return objc_getAssociatedObject(self, @selector(normalBarTintColor));
}

- (void)setNormalBarTintColor:(UIColor *)normalBarTintColor {
    if ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNormal) {
        [self setBarTintColor:normalBarTintColor];
    } else {
        [self setBarTintColor:self.nightBarTintColor];
    }
    objc_setAssociatedObject(self, @selector(normalBarTintColor), normalBarTintColor, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

@end
