//
//  UIView+NightVersion.m
//  UIView+NightVersion
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import "UIView+NightVersion.h"

#import "DKNightVersionManager.h"
#import "DKNightVersionConstants.h"

@implementation UIView (NightVersion)

#pragma mark - SwitchColor

- (void)transformColor {
    [UIView animateWithDuration:NIGHT_ANIMATION_DURATION animations:^{
        self.backgroundColor = ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNight) ? self.nightBackgroundColor : self.normalBackgroundColor;self.tintColor = ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNight) ? self.nightTintColor : self.normalTintColor;
    }];
}

@end
