//
//  UITableView+SeparatorColor.m
//  UITableView+SeparatorColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UITableView+SeparatorColor.h"
#import "DKNightVersionManager.h"
#import "objc/runtime.h"

@interface UITableView ()

@end

@implementation UITableView (SeparatorColor)

- (UIColor *(^)(void))separatorColorPicker {
    return objc_getAssociatedObject(self, @selector(separatorColorPicker));
}

- (void)setSeparatorColorPicker:(UIColor *(^)(void))picker {
    objc_setAssociatedObject(self, @selector(separatorColorPicker), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    self.separatorColor = picker();
    [self.pickers setValue:picker forKey:@"setSeparatorColor:"];
}


@end
