//
//  UITableView+SeparatorColor.h
//  UITableView+SeparatorColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>

@interface UITableView (SeparatorColor)

/**
 * Set this property when switch to night version uitableview SeparatorColor turns to this color.
 */
@property (nonatomic, strong) UIColor *nightSeparatorColor;

/**
 *  UITableView SeparatorColor in normal version.
 */
@property (nonatomic, strong, readonly) UIColor *normalSeparatorColor;

@end
