//
//  UILabel+TextColor.m
//  UILabel+TextColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and
//  test it. And finally open a pull request.

#import "UILabel+TextColor.h"
#import "DKNightVersionManager.h"
#import "objc/runtime.h"

@interface UILabel ()

@end

@implementation UILabel (TextColor)

- (UIColor *(^)(void))textColorPicker {
    return objc_getAssociatedObject(self, @selector(textColorPicker));
}

- (void)setTextColorPicker:(UIColor *(^)(void))picker {
    objc_setAssociatedObject(self, @selector(textColorPicker), picker, OBJC_ASSOCIATION_COPY_NONATOMIC);
    SEL sel = NSSelectorFromString(setTextColor:(UIColor*)textColor);
    [self performSelector:sel withObject:picker()];
    [self.pickers setValue:picker forKey:setTextColor:(UIColor*)textColor];
}


@end
